### PR TITLE
The restaurant page project

### PR DESCRIPTION
**Pull request by keshav-c**
In this PR, I am merging with the skeleton project
- A static landing page for A restaurant
- All code is modular and bundled using webpack

### CODE REVIEW

**Review by shshamim63 — CHANGES_REQUESTED** [review]
## :recycle: Changes Required :recycle: 
___
Hi @keshav-c :wave: 
Awesome job :clap: , your code looks neat and clean. Nav section is functional, pages are generated in separate modules, well-organized code. But your Readme is not complete. It contains empty sections. And the contact section does not contain any info related to you. Please fix them. After generating a descriptive readme please send for another review.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

**Comment by keshav-c** [comment]
The complete README is in the master branch. Because that is the first branch people see when first come to the project page.

**Comment by shshamim63** [comment]
> > But your Readme is not complete.
> 
> The complete README is in the master branch. Because that is the first branch people see when first come to the [project page](https://github.com/keshav-c/Restaurant-Page/).

Based on the instruction in the pathwright, all the tasks are assumed to be a single feature, Readme is also included. Without the approval, nothing should be merged in the production.
image

**Comment by keshav-c** [comment]
I have made the changes to the readme in the feature branch as requested.

**Review by Torres-ssf — APPROVED** [review]
### Project Approved :+1: :clap: 
Hi @keshav-c :hand:
Great job on this project and implementing the requested changes.

**I just want to ask you to edit the PR description before merging this branch**
 As it said [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) in the instructions, it's best practice to summarize in the PR description all changes made in the branch. This will make your repository looks more professional.

Good luck with the next project

Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

**Comment by keshav-c** [comment]
I've made the changes to the first message in the PR as requested.

**Pull request merged**
